name: Continuous Integration

on: push

jobs:
  main:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
        with:
          fetch-depth: 1

      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: '3.7.5'
          architecture: 'x64'

      - name: Install & Test
        run: |
          curl -sSL https://raw.githubusercontent.com/sdispater/poetry/master/get-poetry.py | python
          source $HOME/.poetry/env
          poetry install

          poetry run black --check .
          poetry run pylint sqreen
          poetry run pytest
